#!/bin/bash
#Example of defining variables
# if you are giving space inside your text then use single quotes
a='Ashmit Kumar'
b=boruto
c=chutiya
d=Devansh

echo "I am $a"
echo "I am $b"
echo "I am $c"
echo "I am $d"

